# Generated by Django 5.0.7 on 2024-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='You name')),
                ('Gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('others', 'others')], max_length=200, null=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='You name')),
                ('Gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('others', 'others')], max_length=200, null=True, verbose_name='Gender')),
                ('p_d_details', models.ManyToManyField(to='core.doctor', verbose_name='patient doctor details')),
            ],
        ),
    ]
