# Generated by Django 5.0.7 on 2024-08-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adress',
            field=models.CharField(max_length=200, null=True, verbose_name='You adress'),
        ),
    ]
