# Generated by Django 5.0.7 on 2024-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='Enter you age'),
        ),
    ]
