# Generated by Django 5.0.7 on 2024-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Enter you age'),
        ),
    ]
